version: '3.7'
networks:
  spring-micros-net:
    external: true
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    restart: always
    networks:
      - spring-micros-net
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "9411:9411"
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - spring-micros-net
  zuul-api-gateway:
    image: cosdin/netflix-zuul-api-gateway-server:0.0.1-SNAPSHOT
#    container_name: naming-server
    ports:
      - "8765:8765"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - spring-micros-net
  naming-server:
    image: cosdin/netflix-eureka-naming-server:0.0.1-SNAPSHOT
#    container_name: naming-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - spring-micros-net
  micro2:
    image: cosdin/07-micro-2:0.0.1-SNAPSHOT
#    container_name: micro2
    ports:
      - "5001:5001"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - spring-micros-net
  micro1:
    image: cosdin/07-micro-1:0.0.1-SNAPSHOT
#    container_name: micro1
    ports:
      - "5000:5000"
    restart: always
    environment:
#      SERVICE_URL: http://micro2:5001
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - micro2
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - spring-micros-net
  elastic-search:
    image: elasticsearch:7.10.1
    container_name: 'elastic-search-service'
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - spring-micros-net
  kibana:
    image: kibana:7.10.1
    container_name: 'kibana-service'
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    networks:
      - spring-micros-net
  logstash-service:
    image: logstash:7.10.1
    container_name: 'logstash-service'
    restart: always
    ports:
      - 5100:5100
      - 5044:5044
      - 9600:9600
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - XPACK_MONITORING_ENABLED=true
    networks:
      - spring-micros-net
  spring-boot-admin-service:
    image: cosdin/07-spring-admin-dev:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    restart: always
    networks:
      - spring-micros-net
  spring-config-server-service:
    container_name: 'config-server-service'
    image: cosdin/07-config-server:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
    restart: always
    networks:
      - spring-micros-net
  filebeat-service:
    image: docker.elastic.co/beats/filebeat:7.16.3
    command: filebeat -e -strict.perms=false
    container_name: 'filebeat-service'
    restart: always
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - ./var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    environment:
      - output.elasticsearch.hosts=http://elastic-search:9200
    networks:
      - spring-micros-net