version: '3.7'
networks:
  spring-micros-net:
    external: true
services:
  zuul-api-gateway:
    image: cosdin/netflix-eureka-naming-server:0.0.1-SNAPSHOT
#    container_name: naming-server
    ports:
      - "8765:8765"
    restart: always
    networks:
      - spring-micros-net
  naming-server:
    image: cosdin/netflix-eureka-naming-server:0.0.1-SNAPSHOT
#    container_name: naming-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - spring-micros-net
  micro2:
    image: cosdin/07-micro-2:0.0.1-SNAPSHOT
#    container_name: micro2
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - naming-server
    networks:
      - spring-micros-net
  micro1:
    image: cosdin/07-micro-1:0.0.1-SNAPSHOT
#    container_name: micro1
    ports:
      - "5000:5000"
    restart: always
    environment:
      SERVICE_URL: http://micro2:5001
    depends_on:
#      - micro2
      - naming-server
    networks:
      - spring-micros-net